name=input("Enter your name: ")
id=int(input("Enter your ID: "))
dept=input("Enter your Department: ")
batch=input("Enter your batch: ")
print("neme:",name,"\nID:",id,"\nDepartment:",dept,"\nBatch:",batch)